hacky linux builds

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -179,6 +179,8 @@ supported_hax_target() {
             return 0
         ;;
     esac
+    echo WTF
+    exit 1
     return 1
 }
 
@@ -554,13 +556,16 @@ else
 fi
 
 check_define() {
-cat > $TMPC <<EOF
-#if !defined($1)
-#error $1 not defined
-#endif
-int main(void) { return 0; }
-EOF
-  compile_object
+  if [ "$1" == "__linux__" ]; then
+    echo "WORKAROUND"
+    return 0
+  fi
+  if [ "$1" == "__x86_64__" ]; then
+    echo "WORKAROUND"
+    return 0
+  fi
+  echo "Failed $1"
+  return 1
 }
 
 check_include() {
@@ -605,6 +610,7 @@ else
   bogus_os='yes'
 fi
 
+targetos="Linux"
 # Some host OSes need non-standard checks for which CPU to use.
 # Note that these checks are broken for cross-compilation: if you're
 # cross-compiling to one of these OSes then you'll need to specify
@@ -815,6 +821,7 @@ Linux)
   linux="yes"
   linux_user="yes"
   kvm="yes"
+  hax="yes"
   vhost_net="yes"
   vhost_crypto="yes"
   vhost_scsi="yes"
